spring.application.name=ChatingAppBackend
spring.data.mongodb.uri = mongodb://localhost:27017/ChatApp
#spring.data.mongodb.uri = mongodb+srv://hariomthakur638_db_user:rgky3eErIoXT0TBl@springchatcluster.sjy6xo7.mongodb.net/ChatApp
